server:
  port: 8085
spring:
  application:
    name: dtx-sentinel-service
  cloud:
    nacos:
      discovery:
        namespace: 30b7635b-acaf-42fb-8f26-6457371d525e
        group: seata
        server-addr: 192.168.118.103:8848
    sentinel:
      transport:
        dashboard: 192.168.118.103:8070
        port: 8719